---
###                   ###
#   From local server   #
###                   ###

- hosts: pol3-nas
  become: yes

  roles:
    # For Ubuntu cloud-init
    - role: after_install_ubuntu
      INSTALL_PACKAGES: "false"
      when: ansible_distribution == "Ubuntu"

    - role: ssh_configure
      PORT_SSH: 58022

