---
# defaults file for roles/php_install

version: "74"
packages:
  - php
  - php-cli
  - php-fpm
  - php-mysqlnd
  - php-zip
  - php-devel
  - php-gd
  - php-mcrypt
  - php-mbstring
  - php-curl
  - php-xml
  - php-pear
  - php-bcmath
  - php-json

apache: "no"
