---

- hosts: ubuntu
  become: yes

  tasks:

  - name: Print OS name
    debug:
      msg: "{{ansible_distribution}} version {{ansible_distribution_version}} 
        hostname {{ansible_hostname}} address {{ansible_host}}"

  - name: For Ubuntu 22.04
    debug:
      msg: "Ok!"
    when: ansible_distribution_version == "22.04"
  
  - name: For Ubuntu 20.04
    debug:
      msg: "Ok!"
    when: ansible_distribution_version == "20.04"

- hosts: centos
  become: yes

  tasks:
  
  - name: Print OS name
    debug:
      msg: "{{ansible_distribution}} version {{ansible_distribution_version}} 
        hostname {{ansible_hostname}} address {{ansible_host}}"

  - name: For CentOS
    debug:
      msg: "Ok!"

  - name: Run command
    shell: ls
    register: com_result

  - name: Print preview result
    debug:
      msg: "{{com_result.stdout}}"

