---

 - hosts: all
   become: yes

   tasks:

    - name: Create Directories
      file:
        path: "{{ansible_user_dir}}/my-script"
        state: directory
        owner: virtual
        group: virtual
        mode: 0755
    
    - name: Install script
      template:
        src: /etc/ansible/common/files/teleinfo.sh
        dest: "{{ansible_user_dir}}/my-script/teleinfo.sh"
        owner: virtual
        group: virtual
        mode: 0744

    - name: Install service
      template:
        src: /etc/ansible/common/files/teleinfo.service
        dest: /etc/systemd/system/teleinfo.service
        mode: 0644
      notify:
        teleinfo systemd

    - name: Start service
      systemd:
        name: teleinfo.service
        enabled: yes
        state: started

