---

- hosts: zabbix_clients
  become: yes

  vars:
    port_disable: "false"

  tasks:

  ##### Stop and Disaable service  #####
  - name: Read service facts
    service_facts:

  - name: Stop and Disaable service
    systemd:
      name: zabbix-agent
      state: stopped
      enabled: no
    when: ansible_facts.services["zabbix-agent.service"] is defined and ansible_facts.services["zabbix-agent.service"].state == "running"

  ##### Remove zabbix-agent for Ubuntu #####
  - name: Remove zabbix-agent (Ubuntu)
    shell: "apt purge zabbix-agent -y && apt autoremove -y"
    when: ansible_distribution == "Ubuntu"

  ##### Install zabbix-agent for CentOS #####
  - name: Remove zabbix-agent (CentOS)
    yum:
      name: zabbix-agent
      state: absent
    when: ansible_distribution == "CentOS"

  ##### Remove direcroty /etc/zabbix #####
  - name: Remove direcrory /etc/zabbix
    file:
      path: /etc/zabbix
      state: absent

##### Attention!!! ##### ##### Attention!!! #####

  ##### Close port 10050 #####
  - import_tasks: close.10050.port.yml
    when: port_disable == "true"
  - debug:
      msg: "port 10050 is closed"

##### Attention!!! ##### ##### Attention!!! #####

