##### DEBIAN ######
- name: Add DEB repository for Zabbix v6.0 LTS (Debian 11)
  apt:
    deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-4+debian11_all.deb
    state: present
  when: ansible_distribution_version == "11"

- name: Update cache. Debian
  apt:
    update_cache: true
