  ##### CentOS #####
- name: Add RPM repository for Zabbix v6.0 LTS. CentOS
  yum:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm
    state: present

- name: Update all packages. CentOS
  yum:
    name: '*'
    state: latest

