---
# tasks file for time_moscow

- name: Set zone Europe/Moscow
  shell: timedatectl set-timezone Europe/Moscow
  
- name: Set 24H time format
  lineinfile:
    path: "/etc/default/locale"
    line: "LC_TIME=C.UTF-8"
    state: present
    backup: true
    owner: root
    group: root
    mode: 0644

- name: Debug
  debug:
    msg: "Now please reboot and then check the time and zone settings!!!"

