##### DEBIAN 12 ######
- name: Add DEB repository for Zabbix v6.4 LTS (Debian 12)
  apt:
    deb: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian12_all.deb
    state: present
  when: ansible_distribution_version == "12"

- name: Update cache. Debian
  apt:
    update_cache: true
